### ISSUE TITLE
TeX doesn't like underscores in names

### ISSUE THREAD

**Issue by engineerjai** [onodip/OpenMDAO-XDSM#6]
.tex file halts when the .tikz file contains an unescaped underscore in a component name. E.g. in the Sellar example in the examples folder, the new .tikz contains the name _AutoIVC (when re-generated, current .tikz file is outdated) in line 57. Suggest ensuring underscores are always escaped.

**Comment by onodip** [comment]
Thank for flagging the issue @engineerjai 
I updated the Sellar example, but this does not fix the problem yet. 
https://github.com/onodip/OpenMDAO-XDSM/tree/v0.8

The issue seems to be not simply with the underscores, e.g. when creates without the class names, it will run without error. The auto IVC component is duplicated though, I suspect that this is coming from some change in OpenMDAO, it wasn't like that in previous versions.
```
write_xdsm(prob, filename='sellar_pyxdsm', out_format='pdf', show_browser=True,
               quiet=False, output_side='left', include_indepvarcomps=True, class_names=False)
```

![image](https://github.com/onodip/OpenMDAO-XDSM/assets/34424189/c383f883-3215-4ae6-819e-8766c97389b2)

Later I will try to find the root cause, in the meantime I would suggest to create your diagrams without the class names or use the HTML output format instead.

**Comment by onodip** [comment]
The issue was coming from the underscore in the class name openmdao.core.indepvarcomp:_AutoIndepVarComp
Updated the master branch (but no new tag yet).

**Comment by onodip** [comment]
The new tag fixes the issue with the duplicate _AutoIndepVarComp.
https://github.com/onodip/OpenMDAO-XDSM/tree/v1.0
