### ISSUE TITLE
'Can't find pdflatex, so a pdf can't be generated.' 

### ISSUE THREAD

**Issue by 6thfieldarmy** [onodip/OpenMDAO-XDSM#8]
I did install the pdflatex package, but still get the feedback 'Can't find pdflatex, so a pdf can't be generated.' 
I've also tried to import pdflatex in the same file, which didn't help at all.
shutil.which('pdflatex') indeed return None on my computer, but I'm not sure how should I fix it.

**Comment by onodip** [comment]
@6thfieldarmy try typing in your command window `pdflatex --help`, if this returns an error, your _pdflatex_ installation might be corrupted or missing, otherwise the problem is likely coming from your Python just not finding it. If you are sure that you do have a working pdflatex installation, check that the environmental variable "pdflatex" also exists.

If it fits your needs, you can also use OpenMDAO-XDSM without _pdflatex_. You can set out_format='html', as in [this example](https://github.com/onodip/OpenMDAO-XDSM/blob/v1.1/omxdsm/examples/sellar_xdsmjs.py). This will use _xdsmjs_ to generate the diagram. You can print the html page to PDF, if that is needed, although the quality and looks might be different than with TeX.

**Comment by 6thfieldarmy** [comment]
Great, your suggestion is very helpful;
I'm using Windows and I misunderstood 'pdflatex' as a python package and installed it through pip install pdflatex, of course by so pdflatex didn't work as a command in terminal; then I installed MiKTeX, which fixed the issue, thanks
